### ISSUE TITLE
__init__() got an unexpected keyword argument 'exit_on_error'

### ISSUE THREAD

**Issue by DarknightCanada** [aniqfakhrul/powerview.py#102]
First of all thank you for this great tool.

Any idea why I do keep getting this error `└─$ ls
[2024-07-18 22:07:26] __init__() got an unexpected keyword argument 'exit_on_error'`

this is how I authenticate 

`powerview domain/user:'password'@ip  -k`

**Comment by aniqfakhrul** [comment]
Hi,

thanks! can you check if youre running updated `argparse` python library. If not, can you try upgrading it? If thats the issue, then i need to update the requirements file.

**Comment by DarknightCanada** [comment]
Same issue my man 

` python -c "import argparse; print(argparse.__version__)"
1.1
~$ python3 -c "import argparse; print(argparse.__version__)"
1.1
~$ pip install --upgrade argparse
Defaulting to user installation because normal site-packages is not writeable
Collecting argparse
  Downloading argparse-1.4.0-py2.py3-none-any.whl.metadata (2.8 kB)
Downloading argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Installing collected packages: argparse
Successfully installed argparse-1.4.0
:~$ pip3 install --upgrade argparse
Defaulting to user installation because normal site-packages is not writeable
Collecting argparse
  Using cached argparse-1.4.0-py2.py3-none-any.whl.metadata (2.8 kB)
Using cached argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Installing collected packages: argparse
Successfully installed argparse-1.4.0

**Comment by aniqfakhrul** [comment]
Hm weird. Cant replicate this from my end. What OS/distro are you running on?

**Comment by DarknightCanada** [comment]
`Ubuntu 20.04.1` probably is my vm i will investigate. thank you for your help anyways but before I close this issue what is your recommend method of installation of this tool? maybe i should do it in python env instead.

**Comment by aniqfakhrul** [comment]
I'd personally recommend to manually install with the classic "pip3 install ."

Or just "curl -L powerview.sh | sh". It'll run install.sh available in the repo. Either way should work 🤘

**Comment by DarknightCanada** [comment]
works in python environment
