### ISSUE TITLE
Domain not interpreted

### ISSUE THREAD

**Issue by k4nfr3** [aniqfakhrul/powerview.py#11]
HI, 
1st of all. Congratzs ! This is a great idea. And you are right, most EDR you can't patch AMSI like that, so it makes things more difficult.

I have to add the domain name to the Computer to make resolve. Maybe the -Domain isn't working as planned ?

┌──(kali㉿kali)-[~/PywerView]
└─$ python3 pywerview.py --dc-ip 192.168.16.11 timatec.local/gru:********                      
/usr/lib/python3/dist-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (5.0.0)/charset_normalizer (2.0.6) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
PV> Get-Shares **-Domain timatec.local** -Computer Win10-nothing                                                          
ERROR:root:Resolved Failed: All nameservers failed to answer the query Win10-nothing. IN A: Server 192.168.16.11 TCP port 53 answered SERVFAIL
PV> Get-Shares -Computer Win10-nothing.timatec.local        
Name           Remark                   ComputerName
----           -------                  ------------
ADMIN$         Remote Admin             192.168.16.4
C$             Default share            192.168.16.4
IPC$           Remote IPC               192.168.16.4

**Comment by aniqfakhrul** [comment]
Thanks for the issue. yes, as for now we are just resolving A record from the DC. You might want to use fqdn as DNS resolution is still failing in some cases. But sure, we'll fix this.

**Comment by aniqfakhrul** [comment]
Can you verify if the issue still persists? @k4nfr3

**Comment by k4nfr3** [comment]
yes great. Thank you for the commit
