### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by GeisericII** [aniqfakhrul/powerview.py#111]
Hello! I'm encountering the following when trying to install with pipx:
![immagine](https://github.com/user-attachments/assets/eb8a031c-e957-4b6a-981e-7aa4dfc4c20f)

I think the issue comes from the dev branch, because I remember the dev branch having it, while the main one didn't. 
Thanks!

**Comment by DrorDvash** [comment]
Same error for me and `impacket` is installed on the system (kali)

**Comment by H0j3n** [comment]
Hi, we have added "pyproject.toml" to powerview.py to resolve this issue. Could you please retry using the "dev" branch?

**Comment by DrorDvash** [comment]
> Hi, we have added "pyproject.toml" to powerview.py to resolve this issue. Could you please retry using the "dev" branch?

First I removed `powerview` from my system: 
`pipx uninstall powerview` 
 
then installed successfully using 
`pipx install "git+https://github.com/aniqfakhrul/powerview.py@dev"`

(when trying the main branch still has errors, so I can confirm `dev` branch works now)

**Comment by H0j3n** [comment]
Cool, merged to main !

**Comment by DrorDvash** [comment]
@H0j3n a side note: 
This  tool can be installed using `pipx install powerview`, and will fetch it from pypi (which currently offers version 2024.6.6).

So I prefer to install like above, and to get the latest version from github (also when I'm do `pipx upgrade powerview`) :)
