### ISSUE TITLE
Error when updating ACL, despite working on legacy powerview.

### ISSUE THREAD

**Issue by Thy-GoD** [aniqfakhrul/powerview.py#65]
I'm currently doing a retired HackTheBox machine called Forest.

And have noticed that there's differences between the Add-DomainObjectAcl in powerview.py and legacy powerview, mainly the `-creds or credential` flag is missing. And also the fact that there's an ACL error when I run the same commands in powerview.py, but it does not appear in the legacy version.

Maybe i'm fundementally missing something, but was just wondering if this is an issue with the missing `-creds` flag, the box itself, or I'm not using this command properly.

Thank you for your time.
![image](https://github.com/aniqfakhrul/powerview.py/assets/123708601/a6b6b688-32f4-406c-b57e-2603465c9f22)

**Comment by aniqfakhrul** [comment]
Have you tried re-authenticate with the account?

**Comment by Thy-GoD** [comment]
Oh that's a good point, i'll try that

**Comment by Thy-GoD** [comment]
Thanks, it worked, guess it makes sense, other sources did it in one go so i didn't think of it, sorry for bothering!
