### ISSUE TITLE
Possibility of ACE inheritence/Editing DACLs

### ISSUE THREAD

**Issue by Thy-GoD** [aniqfakhrul/powerview.py#66]
So I was trying to edit the DACL of a user with GenericAll access to an Organizational Unit, in order to do a similar attack mentioned in these resources:

https://github.com/fortra/impacket/pull/1291
and
![image](https://github.com/aniqfakhrul/powerview.py/assets/123708601/da32a809-c2c0-4134-8510-90d5e21e250e)

The closest powerview command I could find was the Add-DomainObjectAcl command, but it would give an error.

![image](https://github.com/aniqfakhrul/powerview.py/assets/123708601/cdd5b868-a645-4044-b359-394d023eb914)

I apologize for the censoring in advance.

I'm not sure if this is the correct command if I were to carry out this sort of attack, the target and principals are correct, and it does work on Impacket's DACLEdit.py script.

![image](https://github.com/aniqfakhrul/powerview.py/assets/123708601/c2196a7b-e239-4cc9-b327-0818b3da9d1c)

Any input would be appreciated, thanks.

**Comment by aniqfakhrul** [comment]
Thanks for input. We will look into this and give you an update.

**Comment by Thy-GoD** [comment]
Thanks alot, I'm loving this tool so far, so I apologize if I continue asking questions regarding it's use.

**Comment by H0j3n** [comment]
No worries, feels free to report any issues. 

Can you verify if the issue still persists? @Thy-GoD 

**Before:**
![image](https://github.com/aniqfakhrul/powerview.py/assets/51261763/49fd7671-2e14-4d37-8dbd-4de3d98c5352)

**After:**
![image](https://github.com/aniqfakhrul/powerview.py/assets/51261763/b92428e6-7f1b-4d1c-ba98-f8646ee7a89a)

**Comment by Thy-GoD** [comment]
Hey guys, I've verified that the fix works and the problem's solved.

![image](https://github.com/aniqfakhrul/powerview.py/assets/123708601/40f5ab7f-6aa2-490e-9297-2cbc7dbb41b5)

Thanks alot for the help!
