### ISSUE TITLE
 [README.md] Typo in manual installation

### ISSUE THREAD

**Issue by Cimihan123** [aniqfakhrul/powerview.py#82]
I think it should be `sudo python3 setup.py install` instead of `sudo pip3 setup.py install` for the manual installation process.

**Comment by aniqfakhrul** [comment]
Hi, thanks for pointing that out. That is indeed our mistake. I'll fix that when im back from vacation 🤧 again thanks!

**Comment by aniqfakhrul** [comment]
Hi, install steps in README is now fixed. Closing this.
