### ISSUE TITLE
Is `-Server` the `-Domain`?

### ISSUE THREAD

**Issue by n3rada** [aniqfakhrul/powerview.py#84]
Is it possible to do the same as the original PowerView:

```powershell
Get-DomainComputer -Domain dev.com -Properties DnsHostName
```

Using your tool seems to be:
```powershell
Get-DomainComputer -Server dev.com -Properties DnsHostName
```

Am I right?

**Comment by aniqfakhrul** [comment]
Yes -Server should serve the same purpose as long as it works as intended. Any errors encountered?

**Comment by n3rada** [comment]
Not at all for now. It was to ensure that I am using it the good way. Thanks!

**Comment by n3rada** [comment]
Not really, the ones that I encountered was purely AD ones.
