### ISSUE TITLE
"is not null" in Where clause

### ISSUE THREAD

**Issue by cmprmsd** [aniqfakhrul/powerview.py#86]
Hey there!

Is there a way to filter for non-null fields in the where clause?

Think of 
```powershell
Get-DomainUser -Select name,description -TableView -Where "description is not null"
```

description != null does not give an error, but I think it matches the string null

**Comment by aniqfakhrul** [comment]
The format should be something like "description not null" iirc. But the -Where function is quite buggy atm. You can try -LDAPFilter '(description=*)' as alternative.
