### ISSUE TITLE
gMSA data are not parsed

### ISSUE THREAD

**Issue by GeisericII** [aniqfakhrul/powerview.py#87]
Hello, first and foremost, thans for this awesome tool!
I wanted to point out that currently gMSA passwords cannot be retrieved by powerview.py and also, ACLs are not parsed. Please see attached screenshots:

Setting user "levi" to be allowed to read gMSA passwords:
![immagine](https://github.com/aniqfakhrul/powerview.py/assets/73939366/8b9ff29e-c2ea-4a62-9c66-8b972c1390aa)

No ACLs over the gMSA
![immagine](https://github.com/aniqfakhrul/powerview.py/assets/73939366/f58ccee5-f59a-405a-bd5a-5c523b9102a2)

Moreover, by looking at the gMSA individually, there is no property that specifies who is allowed to read the gMSA pw.
![immagine](https://github.com/aniqfakhrul/powerview.py/assets/73939366/528ffa73-5691-4c28-8ac6-d073ce68253b)

I think being able to find relevant gMSA ACLs and being able to retrieve password could be a great addition to the tool.
Cheers!

**Comment by aniqfakhrul** [comment]
Hi, can you try using `-GMSAPassword` option under `Get-DomainComputer` module if can successfully parsed the values. If it works, i will probably add parsing function embedded in `Get-DomainComputer` by default.

**Comment by aniqfakhrul** [comment]
Howdy! we have added new module `Get-GMSA`  as an alias of `Get-DomainGMSA` to parse the dacl of each gmsa objects. Feel free to try it out and let us know it goes. Much appreaciated

**Comment by GeisericII** [comment]
Tried and it works wonders! Thanks the awesome work!
