### ISSUE TITLE
Kerbreos authentication fails when NTLM is restricted

### ISSUE THREAD

**Issue by GeisericII** [aniqfakhrul/powerview.py#88]
As per title, Kerberos authentication fails when NTLM authentication is disabled. This happens because powerview attemps to retrieve the machine name using an SMB connection which is not performed using Kerberos:
![immagine](https://github.com/aniqfakhrul/powerview.py/assets/73939366/804edf8c-f07e-447c-afff-f00d2e7b3b99)

Moreover, it also happen when using the AesKey.

**Comment by aniqfakhrul** [comment]
We have fixed this by skipping the smb operation if the domain only supports kerberos auth. Please verify this from your end. Thanks!

**Comment by GeisericII** [comment]
Confirm everything is working, closing the issue, thanks!
